# Generated by Django 4.1.4 on 2023-01-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='matn',
            field=models.TextField(),
        ),
    ]
