# Generated by Django 4.1.4 on 2023-01-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_maqola_matn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervyu',
            name='rasm',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='rasm',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
